# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
- name: PARTICLE_USERNAME
  value: test@example.com
- name: PARTICLE_PASSWORD
  value: 1234
- group: particle-secrets

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '9.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g particle-cli
  displayName: 'Install the Particle CLI'

- script: |
    particle login --username PARTICLE_USERNAME --password PARTICLE_PASSWORD
  displayName: 'Login to Partcle CLI'
